# .gitpod.yml

github:
        prebuilds:
                master: true
                branches: false
                pullRequests: true
                pullRequestsFromForks: false
                addCheck: true
                addComment: false
                addBadge: false
image:
        file: .gitpod.Dockerfile
tasks:
        - name: Init CI Start Script
          init: >
                cd inf && ./.ci_build.sh
